import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Outbound Solutions | Terms of Service",
};

export default function TermsOfService() {
  return (
    <div className="flex flex-col min-h-screen text-foreground bg-background selection:bg-primary/30 py-24 px-6 md:px-12 items-center">
      <div className="w-full max-w-[720px] flex flex-col items-center text-center">
        <span className="font-mono text-primary text-xs tracking-widest uppercase mb-4 border border-primary/30 bg-primary/10 w-fit px-3 py-1 rounded inline-block">
          LEGAL // TERMS OF SERVICE
        </span>
        <h1 className="text-4xl md:text-5xl font-heading mb-4 text-foreground">
          Terms of Service
        </h1>
        <div className="font-mono text-xs text-muted-foreground mb-16 tracking-widest uppercase">
          LAST UPDATED: APRIL 1, 2026
        </div>
      </div>
      
      <div className="w-full max-w-[720px] font-mono text-sm text-muted-foreground leading-relaxed space-y-10 mb-24">
        <section>
          <h2 className="text-white font-bold mb-4 uppercase tracking-wider">Overview</h2>
          <p>These terms govern your use of the Outbound Solutions website and any services provided through an executed engagement. By accessing this site or submitting a Request Access form, you agree to these terms.</p>
        </section>

        <section>
          <h2 className="text-white font-bold mb-4 uppercase tracking-wider">Access and Eligibility</h2>
          <p>The Request Access form is an application, not a guarantee of service. We reserve the right to accept or decline any engagement at our discretion. Services are provided only under a signed engagement agreement with defined scope, deliverables, and pricing.</p>
        </section>

        <section>
          <h2 className="text-white font-bold mb-4 uppercase tracking-wider">Services Description</h2>
          <p>Outbound Solutions builds and operates outbound go-to-market infrastructure including but not limited to: email sending systems, direct mail campaigns, cold calling operations, inbound call handling, LinkedIn outreach, audience targeting, signal detection, and campaign management. Specific deliverables are defined per engagement.</p>
        </section>

        <section>
          <h2 className="text-white font-bold mb-4 uppercase tracking-wider">Client Obligations</h2>
          <p>Clients are responsible for providing accurate business information, responding to booked meetings and transferred calls, and maintaining the internal sales capacity to close pipeline generated by our system. Campaign performance depends on client responsiveness and product-market fit.</p>
        </section>

        <section>
          <h2 className="text-white font-bold mb-4 uppercase tracking-wider">Payment Terms</h2>
          <p>Payment terms are defined in each engagement agreement. Setup fees are due prior to system build. Per-meeting or per-transfer fees are invoiced weekly or monthly as defined in the agreement. Late payments exceeding 15 days may result in campaign suspension.</p>
        </section>

        <section>
          <h2 className="text-white font-bold mb-4 uppercase tracking-wider">Intellectual Property</h2>
          <p>All systems, processes, infrastructure, and methodologies developed by Outbound Solutions remain the intellectual property of Outbound Solutions. Client-specific campaign data, audience lists generated for the client, and meeting outcomes are the property of the client.</p>
        </section>

        <section>
          <h2 className="text-white font-bold mb-4 uppercase tracking-wider">Data and Compliance</h2>
          <p>Outbound Solutions operates in compliance with applicable email sending regulations including CAN-SPAM. Direct mail campaigns comply with USPS regulations. Voice campaigns comply with TCPA regulations. Clients are responsible for ensuring their products and services comply with applicable laws in their industry.</p>
        </section>

        <section>
          <h2 className="text-white font-bold mb-4 uppercase tracking-wider">Limitation of Liability</h2>
          <p>Outbound Solutions provides go-to-market infrastructure and execution. We do not guarantee specific revenue outcomes, close rates, or deal values. Campaign performance is influenced by market conditions, client responsiveness, and product-market fit.</p>
        </section>

        <section>
          <h2 className="text-white font-bold mb-4 uppercase tracking-wider">Termination</h2>
          <p>Either party may terminate an engagement with 30 days written notice. Setup fees are non-refundable. Outstanding per-meeting or per-transfer fees are due within 15 days of termination.</p>
        </section>

        <section>
          <h2 className="text-white font-bold mb-4 uppercase tracking-wider">Modifications</h2>
          <p>We reserve the right to update these terms. Changes take effect upon posting to this page. Continued use of the site constitutes acceptance of updated terms.</p>
        </section>

        <section>
          <h2 className="text-white font-bold mb-4 uppercase tracking-wider">Contact</h2>
          <p>For questions about these terms: legal@outboundsolutions.com</p>
        </section>
      </div>
    </div>
  );
}
